// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_highlight: dynamic(() => import("./BlogHighlight")),
  hero: dynamic(() => import("./Hero")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  process: dynamic(() => import("./Process")),
  project_list: dynamic(() => import("./ProjectList")),
  rich_text: dynamic(() => import("./RichText")),
  text_block: dynamic(() => import("./TextBlock")),
};
