// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  logo: dynamic(() => import("./Logo")),
  rich_text: dynamic(() => import("./RichText")),
};
